### ISSUE TITLE
Tried to push XV

### ISSUE THREAD

**Issue by wightmike** [bioshazard/littlefootcms_DEPRECATED#10]
NOTICE

ssh: connect to host gitlab.eflipdomains.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bioshazard** [comment]
Need to update your remote. I'll show you on Sunday or Tuesday

**Comment by bioshazard** [comment]
Made a new repo, pushed your development branch and duplicated in master branch. Proceed as with Littlefoot project https://github.com/bioshazard/XV
