### ISSUE TITLE
Tried to push Leap2

### ISSUE THREAD

**Issue by wightmike** [bioshazard/littlefootcms_DEPRECATED#11]
NOTICE

Everything up-to-date
- I do not see the push / merge request. Maybe I just don't know how to github.

Admin is done though!

**Comment by bioshazard** [comment]
I was able to push leap2 to github. I will review merge requests with you
soon and get a nice doc together for the whole process

**Comment by bioshazard** [comment]
You reported that you were able push and merge.

Confirmed: https://github.com/bioshazard/littlefootcms/pull/12
