### ISSUE TITLE
HTML where it shouldn't be

### ISSUE THREAD

**Issue by wightmike** [bioshazard/littlefootcms_DEPRECATED#4]
<?=$this->partial('acl-partial-header', array('user' => '', 'inherit' => '', 'global' => 'class="dark_bb"'));?>

That class dark_bb needs to go.

I would remove it myself but idk if it will break the array.

**Comment by bioshazard** [comment]
You replace it with any value you want. It will be available in the acl
header. I can show you tomorrow how partials work.
