### ISSUE TITLE
Admin Dashboard Updates

### ISSUE THREAD

**Issue by wightmike** [bioshazard/littlefootcms_DEPRECATED#5]
Please have hidden nav items show up at the bottom of the navigation list. (hidden nav area no longer needed)

They should be labeled as such:
1. Label hidden

**Comment by wightmike** [comment]
Both hidden and normal nav items should use the same view so they can be edited together. It isn't good to use separate views for each because it hurts consistency.

**Comment by bioshazard** [comment]
merged in

https://github.com/bioshazard/littlefootcms/pull/15
