### ISSUE TITLE
Add link to issue tracker in admin nav

### ISSUE THREAD

**Issue by bioshazard** [bioshazard/littlefootcms_DEPRECATED#7]
We need a link under 'Help' called 'Report Bug' that links to 

https://github.com/bioshazard/littlefootcms/issues/

**Comment by wightmike** [comment]
Should the 'Report Bug' button be added in the LF Admin right under Help?

OR

Should the 'Report Bug' button simply be added to the 'Help' page?
http://littlefootcms.com/byid/23

Also why is that the URL instead of /help?

**Comment by bioshazard** [comment]
I feel it should be a button under Help so there is a better chance of 
bugs getting reported and the function of Help is entirely removed from 
the function of bug report. We may want to change 'Help' to 
'Documentation' or 'User Guide' or something more clear of its function. 
And its by URL cuz I was lazy and didnt want to make a whole controller 
for it. Plus thats just the link to the page, it seems inefficient to do 
it any other way. Thoughts?

**Comment by wightmike** [comment]
I like the word 'Help' for now. I've added the 'Report Bug' button.

Not understanding the URL issue the way you described it. Couldn't you set the page to /help extremely easily? What is /byid?

**Comment by bioshazard** [comment]
Oh, I see now. It is /byid because that is what I copied from the 
lfcms.com wiki. You can replace it with this if you prefer:

http://littlefootcms.com/byname/Admin+Documentation

**Comment by wightmike** [comment]
done
