### ISSUE TITLE
Admin -> User Edit

### ISSUE THREAD

**Issue by wightmike** [bioshazard/littlefootcms_DEPRECATED#8]
When you click Submit after updating the password, the password does not save/update.

There is also no notice of password successfully being changed.

**Comment by bioshazard** [comment]
I need to add notices to many aspects of the admin where updates are 
made (settings, dashboard, etc). I will get on this when the admin 
remodel is merged to development.

**Comment by bioshazard** [comment]
Fixed in https://github.com/bioshazard/littlefootcms/pull/16
